web/router.ex
defmodule Appointments.Router do
  use Appointments.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Openmaize.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Appointments do
    pipe_through :browser

    get "/", PageController, :index

    # Authentication & registration
    get "/registration", RegistrationController, :new
    get "/confirm", PageController, :confirm
    get "/reset", PageController, :askreset
    post "/reset", PageController, :askreset_password
    get "/resetting", PageController, :reset
    post "/resetting", PageController, :reset_password
    get "/login", PageController, :login, as: :login
    post "/login", PageController, :login_user, as: :login
    get "/logout", PageController, :logout, as: :logout

    # Settings
    get "/settings", CompanyController, :edit
    patch "/settings", CompanyController, :update

    # Uploads
    post "/uploads", UploadController, :create

    # Resources
    resources "/employees", EmployeeController
    resources "/companies", CompanyController, only: [:show]
    resources "/services", ServiceController
    resources "/clients", ClientController
  end

  scope "/", Appointments do
    pipe_through :api

    post "/registration", RegistrationController, :create
  end

end

web/views/layout_view.ex
defmodule Appointments.LayoutView do
  use Appointments.Web, :view

  def active?(conn, path) do
    resource = String.split(conn.request_path, "/") |> Enum.at(1)
    if resource == path, do: "active", else: ""
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>book.me</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.7.3/fullcalendar.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.7.3/fullcalendar.print.css" media="print">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" />
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= page_path @conn, :index %>>book.me</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= if @current_user do %>
              <li class="<%= active?(@conn, "calendar") %>"><a href="<%= page_path(@conn, :calendar) %>">Calendar</a></li>
              <li class="<%= active?(@conn, "employees") %>"><a href="<%= employee_path(@conn, :index) %>">Staff</a></li>
              <li class="<%= active?(@conn, "services") %>"><a href="<%= service_path(@conn, :index) %>">Services</a></li>
              <li class="<%= active?(@conn, "clients") %>"><a href="<%= client_path(@conn, :index) %>">Clients</a></li>
              <li class="<%= active?(@conn, "settings") %>"><a href="<%= company_path(@conn, :edit) %>">Settings</a></li>
            <%= end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= if @current_user do %>
              <li>
                <a href="/logout">
                  Logout <%= @current_user.first_name %> (<%= @current_user.company_name %>)
                </a>
              </li>
            <%= else %>
              <li><a href="/registration">Registration</a></li>
              <li><a href="/login">Login</a></li>
            <%= end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>