web/router.ex
defmodule Appointments.Router do
  use Appointments.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Openmaize.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Appointments do
    pipe_through :browser

    get "/", PageController, :index

    # Authentication & registration
    get "/registration", RegistrationController, :new
    get "/confirm", PageController, :confirm
    get "/reset", PageController, :askreset
    post "/reset", PageController, :askreset_password
    get "/resetting", PageController, :reset
    post "/resetting", PageController, :reset_password
    get "/login", PageController, :login, as: :login
    post "/login", PageController, :login_user, as: :login
    get "/logout", PageController, :logout, as: :logout

    # Settings
    get "/settings", CompanyController, :edit
    patch "/settings", CompanyController, :update

    # Uploads
    post "/uploads", UploadController, :create

    # Resources
    resources "/employees", EmployeeController
    resources "/companies", CompanyController, only: [:show]
    resources "/services", ServiceController
    resources "/clients", ClientController
  end

  scope "/", Appointments do
    pipe_through :api

    post "/registration", RegistrationController, :create
  end

end

web/templates/page/calendar.html.eex
<div class="row" style="margin-bottom: 20px;">
  <script type="text/javascript">
    document.access_token = '<%= @access_token %>';
  </script>

  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-reservation">
    Add an appointment
  </button>
</div>

<div class="row">
  <div id="calendar"></div>
</div>

<div class="modal fade" id="add-reservation" role="dialog" aria-labelledby="add-reservation">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add an appointment</h4>
      </div>
      <div class="modal-body">
        <div id="errors" class="alert alert-danger" style="display: none;"></div>

        <button id="client-btn">Appointment</button>
        <button id="personal-btn">Personal</button>

        <form id="reservation-form" method="POST" action="/reservations/">
          <input type="hidden" id="type" name="type" value="" />

          <div id="title" style="margin-bottom: 30px;">
            <h4>Title <small>(optional)</small></h4>
            <input class="form-control" id="title" name="title" placeholder="For example 'on a holiday' or '4th of july'" />
          </div>

          <div id="client" style="margin-bottom: 30px;">
            <h4>Client</h4>
            <fieldset>
              <select class="form-control" id="client-id" name="client_id" style="width: 100%;">
                <option value="">Add a client</option>
                <%= for client <- @clients do %>
                  <option value="<%= client.id %>"><%= Client.full_name(client) %></option>
                <%= end %>
              </select>
            </fieldset>
            <div class="errors" id="client-id-err"></div>
          </div>

          <div id="employee" style="margin-bottom: 30px;">
            <h4>Employee</h4>
            <fieldset>
              <select class="form-control" id="employee-id" name="employee_id" style="width: 100%;">
                <option value="">Any employee</option>
                <%= for employee <- @employees do %>
                  <option value="<%= employee.id %>"><%= Employee.full_name(employee) %></option>
                <%= end %>
              </select>
            </fieldset>
            <div class="errors" id="employee-id-err"></div>
          </div>

          <div id="date-and-time" style="margin-bottom: 30px;">
            <h4>Date &amp; Time</h4>
            <fieldset>
              <div class="row">
                <div class="col-md-2">
                  <label>All day?</label>
                </div>
                <div class="col-md-9">
                  <input type="checkbox" id="all-day" name="all_day" />
                </div>
              </div>
              <div class="row" style="margin-top: 5px;">
                <div class="col-md-2" style="padding-top: 4px;">
                  <label>Start time</label>
                </div>
                <div class="col-md-6">
                  <input type="date" class="form-control" id="start-date" name="start_date" placeholder="Start date" />
                  <div class="errors" id="start-date-err"></div>
                </div>
                <div class="col-md-4">
                  <input type="time" class="form-control" id="start-time" name="start_time" placeholder="Start time" />
                  <div class="errors" id="start-time-err"></div>
                </div>
              </div>
              <div id="end-time-container" class="row" style="display: none; margin-top: 10px;">
                <div class="col-md-2" style="padding-top: 4px;">
                  <label>End time</label>
                </div>
                <div class="col-md-6">
                  <input type="date" class="form-control" id="end-date" name="end_date" placeholder="End date" />
                  <div class="errors" id="end-date-err"></div>
                </div>
                <div class="col-md-4">
                  <input type="time" class="form-control" id="end-time" name="end_time" placeholder="End time" />
                  <div class="errors" id="end-time-err"></div>
                </div>
              </div>
            </fieldset>
          </div>

          <div id="service" style="margin-bottom: 30px;">
            <h4>Service</h4>
            <fieldset>
              <select class="form-control" id="service-id" name="service_id">
                <option value="">Add a service</option>
                <%= for service <- @services do %>
                  <option value="<%= service.id %>" data-duration="<%= service.duration %>">
                    <%= service.name %>
                  </option>
                <%= end %>
                <option value="other" data-duration="60">Other</option>
              </select>
              <div id="service-details" style="display: none;">
                <div class="input-group">
                  <select class="form-control" id="duration-hours" name="duration_hours">
                    <%= for i <- 0..23 do %>
                      <option><%= i %></option>
                    <%= end %>
                  </select>
                  <div class="input-group-addon">hour(s)</div>
                  <select class="form-control" id="duration-minutes" name="duration_minutes">
                    <%= for i <- [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55] do %>
                      <option><%= i %></option>
                    <%= end %>
                  </select>
                  <div class="input-group-addon">minutes</div>
                </div>
              </div>
            </fieldset>
            <div class="errors" id="service-id-err"></div>
          </div>

          <div id="notes" style="margin-bottom: 10px;">
            <h4>Notes <small>(optional)</small></h4>
            <fieldset>
              <textarea class="form-control" id="notes" name="notes"></textarea>
            </fieldset>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="reservation-submit" type="button" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>

web/templates/page/login.html.eex
<h2>Login</h2>

<%= form_for @conn, login_path(@conn, :login_user), [as: :user], fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-error">
      <p>Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn" %>
  </div>
<% end %>

<%= link "Forgot your password?", to: page_path(@conn, :askreset) %>

web/templates/page/registration.html.eex
<h2>Create an account</h2>

<form accept-charset="UTF-8" action="<%= page_path(@conn, :registration_post) %>" class="form-horizontal" method="post">
  <input type="hidden" name="_csrf_token" value="<%= csrf_token(@conn) %>">
  <input name="_utf8" type="hidden" value="✓">

  <div class="form-group">
    <label for="reg_first_name" class="col-sm-2 control-label">Your Name</label>
    <div class="col-sm-10">
      <input class="form-control" id="employee_name" name="employee[name]" placeholder="Your Full Name" type="text">
    </div>
  </div>
  <div class="form-group">
    <label for="reg_email" class="col-sm-2 control-label">Your Email</label>
    <div class="col-sm-10">
      <input class="form-control" id="employee_email" name="employee[email]" placeholder="We won't give it to anyone, promise!" type="text">
    </div>
  </div>
  <div class="form-group">
    <label for="reg_company_name" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-10">
      <input class="form-control" id="company_name" name="company[company_name]" placeholder="The name of your company" type="text">

    </div>
  </div>
  <!--
  <div class="form-group">
    <label for="reg_company_name" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-10">
      <div class="input-group">
        <div class="input-group-addon">
          https://
        </div>
        <input class="form-control" id="reg_company_slug" name="reg[company_slug]" placeholder="mycompany" type="text">
        <div class="input-group-addon">.bookme.com</div>
     </div>
   </div>
  </div>
-->
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input class="btn btn-default" type="submit" value="Start Your Free Trial">
    </div>
  </div>
</form>

web/templates/page/reset.html.eex
<h2>Reset password</h2>

<%= form_for @conn, page_path(@conn, :askreset), [as: :user], fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-error">
      <p>Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Please enter your email address</h4>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn" %>
  </div>
<% end %>

web/templates/page/resetting.html.eex
<h2>Reset your password</h2>

<%= form_for @conn, page_path(@conn, :reset_password), [as: :user], fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-error">
      <p>Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Confirm password</label>
    <%= password_input f, :confirm_password, class: "form-control" %>
  </div>

  <%= hidden_input f, :email, value: @email %>
  <%= hidden_input f, :key, value: @key %>

  <div class="form-group">
    <%= submit "Submit", class: "btn" %>
  </div>
<% end %>

<%= link "Back", to: page_path(@conn, :index) %>