web/router.ex
defmodule Appointments.Router do
  use Appointments.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Openmaize.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Appointments do
    pipe_through :browser

    get "/", PageController, :index

    # Authentication & registration
    get "/registration", RegistrationController, :new
    get "/confirm", PageController, :confirm
    get "/reset", PageController, :askreset
    post "/reset", PageController, :askreset_password
    get "/resetting", PageController, :reset
    post "/resetting", PageController, :reset_password
    get "/login", PageController, :login, as: :login
    post "/login", PageController, :login_user, as: :login
    get "/logout", PageController, :logout, as: :logout

    # Settings
    get "/settings", CompanyController, :edit
    patch "/settings", CompanyController, :update

    # Uploads
    post "/uploads", UploadController, :create

    # Resources
    resources "/employees", EmployeeController
    resources "/companies", CompanyController, only: [:show]
    resources "/services", ServiceController
    resources "/clients", ClientController
  end

  scope "/", Appointments do
    pipe_through :api

    post "/registration", RegistrationController, :create
  end

end

web/templates/shared/image_uploader.html.eex
<!--
     This uploader component uploads an image to the server and
     gets back a path for the image in the uploads folder. This
     path is made available to external components through the
     data-url attribute on the form.
 -->
<div class="image-uploader">
  <img src="<%= @source %>"/>
</div>
<form id="image-upload-form" action="<%= upload_path(@conn, :create) %>"
      method="post">
  <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">
  <input type="file" name="image" class="hidden" id="image-upload-input"/>
</form>

<style>
.image-uploader img {
    width: 80%;
    max-height: 250px;
    max-width: 250px;
    object-fit: cover;
    display: block;
    margin: 0 auto;
}
</style>